mail_settings:
  case1:
    on_failure:
      send_to:
        - someAdress@gmail.com
        - anotherAdress@gmail.com
    on_success:
      send_to:
        - someAdress@gmail.com

  case2:
    on_success:
      send_to:
        - someAdress@gmail.com