mail_settings:
  case1:
    failure:
      send_to:
        - someAdress@gmail.com
        - anotherAdress@gmail.com
    success:
      send_to:
        - someAdress@gmail.com

  case2:
    success:
      send_to:
        - someAdress@gmail.com